javascript/wheres-waldo/config/routes.rb
Rails.application.routes.draw do
  root 'albums#index'

  resources :albums do
    resources :pictures, except: [:index] do
      get 'selections'
      resources :locations, except: [:show, :new, :edit]
      resources :scores, only: [:index, :create, :destroy] do
        get 'load', on: :member
        get 'quit', on: :collection
        get 'hints'
        get 'matches'
        post 'guess'
      end
    end
  end

  resources :characters

  resources :users do
    resources :scores
  end

  # Sessions
  get 'login', to: 'sessions#new_login'
  post 'login', to: 'sessions#login'
  get 'logout', to: 'sessions#logout'
end

javascript/wheres-waldo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include ApplicationHelper

  add_flash_types :success, :failure, :warning

  def require_login
    unless logged_in?
      flash[:warning] = "You must be logged in to do that."
      redirect_to login_path
    end
  end

  def require_admin
    unless admin_user?
      flash[:warning] = "You must be an admin to do that."
      redirect_back fallback_location: root_path
    end
  end

end

javascript/wheres-waldo/app/helpers/application_helper.rb
module ApplicationHelper

  include SessionsHelper
  include ScoresHelper

end

javascript/wheres-waldo/app/views/application/_flashes.html.erb
<% if flash.any? %>

  <ul class="flash">

    <% flash.each do |key, message| %>

      <%= tag.li message, class: key %>

    <% end %>

  </ul>

  <hr />

<% end %>

javascript/wheres-waldo/app/views/application/_header.html.erb
<header>

  <nav>
    <h1>
      <%= link_to "Where's", albums_path %>
      <%= link_to "Waldo?", characters_path %>
    </h1>

    <% if score_set? && !@playing_game %>
      <div id="score-display" initial-time="<%= current_score.total_time %>" >
        <timer v-bind:total="elapsedTime"></timer>
        <h3>You currently have a match in progress.</h3>
        <%= link_to "Continue", load_album_picture_score_path(current_score.picture.album, current_score.picture, current_score) %>
        <%= link_to "Quit", quit_album_picture_scores_path(current_score.picture.album, current_score.picture) %>
      </div>
    <% end %>

    <div>
      <%= link_to "Sign Up", new_user_path unless logged_in? %>
      <%= link_to "Login", login_path unless logged_in? %>

      <%= link_to "Account", user_path(current_user) if logged_in? %>
      <%= link_to "Logout", logout_path if logged_in? %>
    </div>
  </nav>

  <hr />

  <%= render 'flashes' %>

</header>