ruby_on_rails/kittens-api/config/routes.rb
Rails.application.routes.draw do
  root 'kittens#index'
  resources :kittens
end

ruby_on_rails/kittens-api/app/models/kitten.rb
class Kitten < ApplicationRecord

	validates :name, presence: { message: "has to exist.  Who doesn't even give their cat a name?" },
					 uniqueness: { case_insensitive: true, message: "needs to be special.  Not everyone's cat can have the same name.  That would be chaos." },
					 length: { minimum: 2, maximum: 64, message: "should be of a reasonable length.  No one-letter names or anything that can't be pronounced in one breath." }
	
	validates :age, presence: { message: "is not only required here, but I hope for your sake, you are at least aware of, lest your feline-friend drops dead on the next outing" },
					numericality: { greater_than_or_equal_to: 0, less_than: 40, message: "has to be within a normal cat's lifetime, come on." }
	
	validates :cuteness, presence: { message: "is a factor all kitten-owners must assign with their best of judgement, and you just skipped that part." },
						 numericality: { greater_than: 0, less_than: 11, message: "should, of course, fall within the strict 1-10 guideline mandatory for all ratings systems." }

	validates :softness, presence: { message: "is on the list here, isn't it?" },
						 numericality: { greater_than: 0, less_than: 11, message: "must, like all fair ratings, be a choice of number from one to ten." }

end

ruby_on_rails/kittens-api/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ruby_on_rails/kittens-api/app/controllers/kittens_controller.rb
class KittensController < ApplicationController

	def index
		@kittens = Kitten.all
		respond_to do |format|
			format.html
			format.json { render json: @kittens }
		end
	end

	def show
		@kitten = Kitten.find(params[:id])
		respond_to do |format|
			format.html
			format.json { render json: @kitten }
		end
	end

	def new
		@kitten = Kitten.new
	end

	def create
		@kitten = Kitten.new(kitten_params)
		if @kitten.save
			flash[:success] = "Kitten was created!"
			redirect_to @kitten
		else
			flash[:failure] = "Kitten couldn't be created."
			render :new
		end
	end

	def edit
		@kitten = Kitten.find(params[:id])
	end

	def update
		@kitten = Kitten.find(params[:id])
		if @kitten.update_attributes(kitten_params)
			flash[:success] = "Kitten was updated!"
			redirect_to @kitten
		else
			flash[:failure] = "Kitten couldn't be updated."
			render :edit
		end
	end

	def destroy
		@kitten = Kitten.find(params[:id])
		if @kitten.destroy
			flash[:success] = "Kitten was destroyed!"
			redirect_to kittens_path
		else
			flash[:failure] = "Kitten couldn't be destroyed."
			redirect_back fallback_location: kittens_path
		end
	end


	private

		def kitten_params
			params.require(:kitten).permit(:name, :age, :cuteness, :softness)
		end

end

ruby_on_rails/kittens-api/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby_on_rails/kittens-api/app/helpers/kittens_helper.rb
module KittensHelper
end

ruby_on_rails/kittens-api/app/views/kittens/_errors.html.erb
<% if @kitten.errors.any? %>
	<h3>Reasons Why We Can't Have Nice Things:</h3>
	<ol>
		<% @kitten.errors.keys.each do |key| %>
			<li><%= @kitten.errors.full_messages_for(key).first %></li>
		<% end %>
	</ol>
	<hr>
<% end %>

ruby_on_rails/kittens-api/app/views/kittens/_form.html.erb
<%= form_for @kitten do |f| %>
	<div>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>

	<div>
		<%= f.label :age %>
		<%= f.text_field :age %>
	</div>

	<div>
		<%= f.label :cuteness %>
		<%= f.text_field :cuteness %>
	</div>

	<div>
		<%= f.label :softness %>
		<%= f.text_field :softness %>
	</div>

	<%= f.submit %>
<% end %>

ruby_on_rails/kittens-api/app/views/kittens/edit.html.erb
<h1>Edit <%= @kitten.name %></h1>

<%= render 'errors' %>

<%= link_to "Delete this Kitten", kitten_path(@kitten), method: :delete %>

<%= render 'form' %>

ruby_on_rails/kittens-api/app/views/kittens/index.html.erb
<h1>Kittens</h1>
<%= link_to "Create a Kitten", new_kitten_path %>
<ul>
	<% @kittens.each do |kitten| %>
		<li><%= link_to kitten.name, kitten %> | <%= link_to "Delete this Kitten", kitten_path(kitten), method: :delete %></li>
	<% end %>
</ul>

ruby_on_rails/kittens-api/app/views/kittens/new.html.erb
<h1>Create New Kitten</h1>

<%= render 'errors' %>

<%= render 'form' %>

ruby_on_rails/kittens-api/app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>

<%= link_to "Edit this Kitten", edit_kitten_path(@kitten) %>
<%= link_to "Delete this Kitten", kitten_path(@kitten), method: :delete %>

<ul>
	<li>Age: <%= @kitten.age %></li>
	<li>Cuteness: <%= @kitten.cuteness %></li>
	<li>Softness: <%= @kitten.softness %></li>
</ul>