ruby_on_rails/flight-booker/config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'
  get '/flights', to: 'flights#index'

  resources :bookings, only: [:new, :create, :show]
end

ruby_on_rails/flight-booker/app/models/airport.rb
class Airport < ApplicationRecord
	has_many :departing_flights, class_name: 'Flight',
								 foreign_key: :origin_id,
								 inverse_of: :origin
	has_many :arriving_flights, class_name: 'Flight',
								foreign_key: :destination_id,
								inverse_of: :destination 

	validates :code, presence: true,
					 uniqueness: true,
					 length: { is: 3 }
end

ruby_on_rails/flight-booker/app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers

  accepts_nested_attributes_for :passengers
end

ruby_on_rails/flight-booker/app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :origin, class_name: 'Airport',
  					  inverse_of: :departing_flights
  belongs_to :destination, class_name: 'Airport',
  						   inverse_of: :arriving_flights
  has_many :bookings

  validates_presence_of :origin, :destination, :departure, :duration
  validates :duration, numericality: { greater_than_or_equal_to: 30 }
  validate :origin_is_not_destination

  def departure_formatted
    departure.strftime("%m/%d/%Y AT %H:%M%p")
  end

  def departure_date_formatted
  	departure.strftime("%m/%d/%Y")
  end

  # Credit to https://stackoverflow.com/a/1224769
  def duration_in_words
  	minutes = (duration / 60).round
  	hours = minutes / 60
  	minutes = minutes - (hours * 60)

    words = ""
  	words << "#{hours} #{ (hours == 1) ? 'hour' : 'hours' }" if hours > 0
    words << ", " if hours > 0 && minutes > 0
  	words << "#{minutes} #{ (minutes == 1) ? 'minute' : 'minutes' }" if minutes > 0

    words
  end


  private

  	# Validators

  	def origin_is_not_destination
  		if origin == destination
  			errors.add( :destination, "can't be Origin")
  		end
  	end
end

ruby_on_rails/flight-booker/app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking

  validates_presence_of :name, :email
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX }
end

ruby_on_rails/flight-booker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ruby_on_rails/flight-booker/app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
	before_action :ensure_search_params_present, only: :new

	def show
		@booking = Booking.includes(:passengers, flight: [:origin, :destination]).find(params[:id])
	end

	def new
		@flight = Flight.includes(:origin, :destination).find(params[:flight_id])
		@booking = @flight.bookings.build
		@passenger_count ||= params[:passengers].to_i
		@passenger_count.times { @booking.passengers.build }
	end

	def create
		@booking = Booking.new(booking_params)
		@flight = @booking.flight
		@passenger_count = @booking.passengers.count
		if @booking.save
			flash[:success] = "Booking Created!"
			redirect_to booking_path @booking
		else
			flash.now[:failure] = "There was a problem booking your flight."
			render :new
		end
	end


	private

		def booking_params
			params.require(:booking).permit(:flight_id, passengers_attributes: [:id, :name, :email])
		end

		def ensure_search_params_present
			unless params[:flight_id].present? && ( params[:passengers].to_i > 0 )
				flash[:errorA] = "Please choose a flight first." if params[:flight_id].blank?
				flash[:errorB] = "Please search the number of passengers first." unless params[:passengers].to_i > 0
				redirect_back( fallback_location: root_path )
			end
		end
end

ruby_on_rails/flight-booker/app/controllers/flights_controller.rb
class FlightsController < ApplicationController
	include FlightsHelper
	before_action :ensure_different_airports

	def index
		@airport_options = Airport.all.map { |airport| [airport.code, airport.id] }
		@flight_time_options = Flight.order(:departure).map { |flight| [flight.departure_date_formatted, flight.departure.to_date] }.uniq

		if search_params_present?
			@flights = Flight.all.includes(:origin, :destination)
			@flights = @flights.where( origin_id: params[:origin] ) if params[:origin].present?
			@flights = @flights.where( destination_id: params[:destination] ) if params[:destination].present?
			@flights = @flights.where( 'departure BETWEEN ? AND ?', params[:departure].to_datetime, ( params[:departure].to_datetime + 1.day ) ) if params[:departure].present?
		end
	end


	private

		def ensure_different_airports
			if params[:origin].present? && ( params[:origin] == params[:destination] )
				flash.now[:error] = "There are no flights departing from and arriving at same airport."
			end
		end
end

ruby_on_rails/flight-booker/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby_on_rails/flight-booker/app/helpers/bookings_helper.rb
module BookingsHelper
end

ruby_on_rails/flight-booker/app/helpers/flights_helper.rb
module FlightsHelper
	def search_params_present?
		params[:origin].present? || params[:destination].present? || params[:passengers].present? || params[:departure].present?
	end

	# Relying on instance variables from the controller doesn't feel safe here...
	def search_title_builder
		if search_params_present?
			title = "Searching Flights"
			title += " Departing #{ @airport_options[params[:origin].to_i - 1][0] }" if params[:origin].present?
			if params[:destination].present?
				if params[:origin].present?
					title += " for "
				else
					title += " to "
				end
				title += "#{ @airport_options[params[:destination].to_i - 1][0] }"
			end
			title += " on #{ params[:departure] }" if params[:departure].present?
			title += " for #{ params[:passengers] }" if params[:passengers].present?
			return title
		else
			title = "Search Flights"
		end
	end
end

ruby_on_rails/flight-booker/app/views/flights/_flight_list.html.erb
<% if @flights %>
	<%= form_tag new_booking_path, method: :get do %>
		<%= hidden_field_tag :passengers, params[:passengers].to_i %>
		<%= submit_tag "Book a Flight" %>
		<% @flights.each do |flight| %>
			<h3><%= "Flight ##{flight.id}" %></h3>
			<ul>
				<li><%= "ORIGIN: #{flight.origin.code}" %></li>
				<li><%= "DESTINATION: #{flight.destination.code}" %></li>
				<li><%= "DEPARTING AT: #{flight.departure_formatted}" %></li>
				<li><%= "DURATION: #{flight.duration_in_words}" %></li>
			</ul>
			<%= radio_button_tag :flight_id, flight.id %>
			<%= label_tag :flight_id, "Book this flight" %>
			<hr>
		<% end %>
	<% end %>
<% end %>

ruby_on_rails/flight-booker/app/views/flights/_flight_search.html.erb
<h1><%= search_title_builder %></h1>

<%= form_tag flights_path, method: :get do |f| %>
	<%= label_tag :origin, "FROM:" %>
	<%= select_tag :origin, options_for_select( @airport_options ), { prompt: "" } %>

	<%= label_tag :destination, "TO:" %>
	<%= select_tag :destination, options_for_select( @airport_options ), { prompt: "" } %>

	<%= label_tag :passengers, "PASSENGERS:" %>
	<%= select_tag :passengers, options_for_select( [1,2,3,4] ), { prompt: "" } %>

	<%= label_tag :departure, "DATE:" %>
	<%= select_tag :departure, options_for_select( @flight_time_options ), { prompt: "" } %>

	<%= submit_tag "Search Flights" %>
<% end %>

ruby_on_rails/flight-booker/app/views/flights/index.html.erb
<%= render 'flight_search' %>
<hr>
<br>
<%= render 'flight_list' %>